let userData = [];
let index = 0;
let processing = false;
let count = 0;
let tabData;
let discardData;

let mailTabData;

const links=[
   "/company/aarya-durga-security-solutions-private-limited",
  "/company/aarya-express-solutions-i-private-limited",
  "/company/aarya-gas-microtunnel-solutions-private-limited",
  "/company/aarya-global-legend-private-limited",
  "/company/aarya-hotel-&&-resort-private-limited",
  "/company/aarya-landmark-and-developers-india-private-limited",
  "/company/aarya-rudraksha-opc-private-limited",
  "/company/aarya-sikshantar-foundation",
  "/company/aarya-trading-private-limited",
  "/company/aaryaa-airlines-private-limited",
  "/company/aaryahights-opc-private-limited",
  "/company/aaryakrish-infracon-private-limited",
  "/company/aaryam-digitech-private-limited",
  "/company/aaryam-eco-exports-private-limited",
  "/company/aaryam-helping-hands-private-limited",
  "/company/aaryam-trending-private-limited",
  "/company/aaryama-international-private-limited",
  "/company/aaryaman-development-foundation",
  "/company/aaryan-information-technologies-private-limited",
  "/company/aaryan-times-private-limited",
  "/company/aaryan-weavetex-private-limited",
  "/company/aaryangloss-private-limited",
  "/company/aaryansh-dream-infra-private-limited",
  "/company/aaryansh-projects-private-limited",
  "/company/aaryash-agritech-&&-biotech-private-limited",
  "/company/aaryashiv-tax-solutions-private-limited",
  "/company/aaryashree-mobile-india-private-limited",
  "/company/aaryav-capital-private-limited",
  "/company/aaryavartcentre-for-autism-and-special-needs-foundation",
  "/company/aaryavartt-frequency-solutions-private-limited",
  "/company/aaryavrat-packaging-solutions-private-limited",
  "/company/aaryavridhi-retail-private-limited",
  "/company/aaryawart-astro-world-private-limited",
  "/company/aas-eduguide-private-limited",
  "/company/aas-engineering-solution-opc-private-limited",
  "/company/aas-entrepreneur-solutions-private-limited",
  "/company/aas-health-care-&&-skill-development-foundation",
  "/company/aas-instruments-private-limited",
  "/company/aas-international-private-limited",
  "/company/aas-nanashi-agro-private-limited",
  "/company/aasaar-industries-private-limited",
  "/company/aasakya-digital-technologies-private-limited",
  "/company/aasamant-agrotech-park-foundation",
  "/company/aasawa-brothers-aif-private-limited",
  "/company/aasesha-infrastructure-solutions-private-limited",
  "/company/aash-hope-foundation",
  "/company/aash-infra-private-limited",
  "/company/aasha-devi-industries-private-limited",
  "/company/aasha-excel-private-limited",
  "/company/aasha-skyliners-private-limited",
  "/company/aashaam-tour-and-hospitality-private-limited",
  "/company/aashabadi-foundation",
  "/company/aashadeep-education-private-limited",
  "/company/aashapura-buildwork-private-limited",
  "/company/aashar-prodip-welfare-foundation",
  "/company/aasharaalo-shg-service-foundation",
  "/company/aashaya-abhimukh-farmer-producer-company-limited",
  "/company/aashaya-innovations-private-limited",
  "/company/aashayein-bejubano-ki-foundation",
  "/company/aashdwar-netsol-private-limited",
  "/company/aashi-abhushan-private-limited",
  "/company/aashi-education-private-limited",
  "/company/aashi-kedia-foundation",
  "/company/aashi-networks-private-limited",
  "/company/aashi-venture-private-limited",
  "/company/aashik-bara-shipping-private-limited",
  "/company/aashima-skill-foundation",
  "/company/aashiprime-private-limited",
  "/company/aashiriti-financial-advisory-&&-services-private-limited",
  "/company/aashirwad-shri-balaji-industries-private-limited",
  "/company/aashirwad-suraksha-private-limited",
  "/company/aashirwad-vrushit-trading-private-limited",
  "/company/aashish-cherity-federation",
  "/company/aashita-overseas-private-limited",
  "/company/aashiyana-blessings-opc-private-limited",
  "/company/aashna-farms-private-limited-U01500RJ2024PTC093359",
  "/company/aashprox-private-limited",
  "/company/aashra-goods-private-limited-U68100WB2024PTC271076",
  "/company/aashray-organics-private-limited",
  "/company/aashray-ship-management-private-limited",
  "/company/aashraya-medical-centre-private-limited",
  "/company/aashreyinfrastructure-venturesindia-private-limited",
  "/company/aashrika-mining-private-limited",
  "/company/aashrya-study-consultants-private-limited",
  "/company/aashta-agro-hi-tech-producer-company-limited",
  "/company/aashtech-innovation-private-limited",
  "/company/aashthi-property-services-private-limited",
  "/company/aashti-wardha-agro-producer-company-limited",
  "/company/aashul-consultancy-opc-private-limited",
  "/company/aashutam-swashtam-costumes-opc-private-limited",
  "/company/aashutvaam-services-opc-private-limited",
  "/company/aashvee-infra-private-limited",
  "/company/aashvi-biotech-opc-private-limited",
  "/company/aashvi-enterprises-private-limited",
  "/company/aashvi-essentials-marketing-private-limited",
  "/company/aashvi-infrazone-ats-private-limited",
  "/company/aasita-development-and-realty-private-limited",
  "/company/aasiya-finance-private-limited",
  "/company/aasiya-landbase-private-limited",
  "/company/aasiyana-intergrated-farmers-producer-company-limited",
  "/company/aask-lifts-&&-escalators-private-limited",
  "/company/aaska-agro-private-limited",
  "/company/aaskom-enterprises-private-limited",
  "/company/aasma-khan-shipping-management-private-limited",
  "/company/aasmani-aquafarming-private-limited",
  "/company/aasoni-india-it-opc-private-limited",
  "/company/aasove-foods&&beverages-private-limited",
  "/company/aaspad-tradelink-private-limited",
  "/company/aaspira-freight-india-private-limited",
  "/company/aasraya-design-studio-private-limited",
  "/company/aasrha-international-foundation",
  "/company/aasri-cold-storage-solutions-opc-private-limited",
  "/company/aasritha-imports-and-exports-private-limited",
  "/company/aasta-lifespace-private-limited",
  "/company/aastena-enterprises-private-limited",
  "/company/aastha-cold-storage-private-limited",
  "/company/aastha-gems-&&-jewellers-private-limited",
  "/company/aastha-opticals-private-limited",
  "/company/aastha-retailers-private-limited",
  "/company/aasthik-builders-private-limited",
  "/company/aastik-securities-private-limited",
  "/company/aastitva-chem-private-limited",
  "/company/aastitvaventures-private-limited",
  "/company/aastitwa-manpower-world-private-limited",
  "/company/aastra-lifts-private-limited",
  "/company/aasui-atf-rice-mill-private-limited",
  "/company/aasumi-mech-projects-private-limited",
  "/company/aasvaa-universal-private-limited",
  "/company/aasvika-buildmax-private-limited",
  "/company/aasyou-digital-market-solution-private-limited",
  "/company/aatamgyan-yogpeeth-foundation",
  "/company/aatap-ventures-opc-private-limited",
  "/company/aatar-technology-solutions-private-limited",
  "/company/aatavata-business-private-limited",
  "/company/aatcose-construction-and-services-private-limited",
  "/company/aatg-enterprises-private-limited",
  "/company/aathang-exim-services-private-limited",
  "/company/aatharv-ecobuild-private-limited",
  "/company/aatharv-womenswear-private-limited",
  "/company/aathinarayani-industries-private-limited",
  "/company/aathiraa-solutions-private-limited",
  "/company/aathiraa-trading-private-limited",
  "/company/aathiyam-foods-private-limited",
  "/company/aathmeeya-bioenergy-private-limited",
  "/company/aathya-technology-services-private-limited",
  "/company/aatiya-industries-private-limited",
  "/company/aatma-jagrut-church-india-foundation",
  "/company/aatmanand-agro-industries-private-limited",
  "/company/aatmanirbhar-kushalgarh-private-limited",
  "/company/aatmanirbhar-renewable-solar-private-limited",
  "/company/aatmantree-foundation",
  "/company/aatmika-infra-private-limited",
  "/company/aatmnirbhar-green-solutions-private-limited",
  "/company/aatralai-tech-solutions-private-limited",
  "/company/aatri-experiential-travel-private-limited",
  "/company/aaudumbar-agro-private-limited",
  "/company/aauraunix-private-limited",
  "/company/aauriga-quantrade-private-limited",
  "/company/aautoggenix-machining-and-technologies-private-limited",
  "/company/aav-projects-private-limited",
  "/company/aav-roommate-private-limited",
  "/company/aava-enterprises-private-limited",
  "/company/aavad-texco-private-limited",
  "/company/aavah-kids-store-private-limited",
  "/company/aavani-gold-&&-diamond-private-limited",
  "/company/aavani-professional-services-private-limited",
  "/company/aavarana-store-opc-private-limited",
  "/company/aavartan-buildtech-private-limited",
  "/company/aavartan-eco-solutions-private-limited",
  "/company/aavazz-universal-music-art-foundation",
  "/company/aavedam-hospitality-private-limited",
  "/company/aaveg-foundation",
  "/company/aavesham-studio-private-limited",
  "/company/aavgo-technologies-private-limited",
  "/company/aavik-eco-technology-private-limited",
  "/company/aavin-sustainable-private-limited",
  "/company/aavishkara-global-education-private-limited",
  "/company/aavishkri-consultancy-and-services-private-limited",
  "/company/aavk-food-&&-services-private-limited",
  "/company/aavm-global-logistics-private-limited",
  "/company/aavtar-finechem-private-limited",
  "/company/aavyansh-hospital-world-private-limited",
  "/company/aavyooh-guna-solutions-private-limited",
  "/company/aavyukth-cow-products-private-limited",
  "/company/aawap-advertising-private-limited",
  "/company/aawoni-designs-private-limited",
  "/company/aaxdd-construction-private-limited",
  "/company/aay-jay-polymer-private-limited",
  "/company/aaya-essentials-private-limited",
  "/company/aayaamx-technologoies-private-limited",
  "/company/aayam-infra-projects-private-limited",
  "/company/aayan-global-webtech-limited",
  "/company/aayansh-small-finance-private-limited",
  "/company/aayansh-technologies-and-services-private-limited",
  "/company/aayanshka-projects-private-limited",
  "/company/aayas-mineral-exploration-services-private-limited",
  "/company/aayat-charitable-foundation",
  "/company/aayat-engineering-private-limited",
  "/company/aayat-overseas-private-limited",
  "/company/aayat-residency-owners-service-association",
  "/company/aayatana-tech-private-limited",
  "/company/aaykam-impex-private-limited",
  "/company/aayo-dimensions-private-limited",
  "/company/aayodhya-cloud-technologies-private-limited",
  "/company/aayozon-global-services-private-limited",
  "/company/aayp-trade-links-private-limited",
  "/company/aayra-exim-private-limited-U46620HR2024PTC122518",
  "/company/aayra-exim-private-limited",
  "/company/aays-solutions-private-limited",
  "/company/aayu-edutech-private-limited",
  "/company/aayu-health-sciences-private-limited",
  "/company/aayu-infotech-private-limited",
  "/company/aayu-international-private-limited",
  "/company/aayu-nirman-private-limited",
  "/company/aayudelite-hospitality-services-private-limited",
  "/company/aayudh-nahar-private-limited",
  "/company/aayudhan-consultancy-service-private-limited",
  "/company/aayudigi-health-private-limited",
  "/company/aayugrow-ayurveda-opc-private-limited",
  "/company/aayum-ispat-and-energy-limited",
  "/company/aayupran-finbuzz-legit-services-private-limited",
  "/company/aayurdham-life-sciences-private-limited",
  "/company/aayurphysio-wellness-centre-private-limited",
  "/company/aayush-infomedia-private-limited",
  "/company/aayush-it-services-private-limited",
  "/company/aayush-medicaments-private-limited",
  "/company/aayush-retail-marketing-private-limited",
  "/company/aayush-solar-energy-plant-private-limited",
  "/company/aayush-technical-services-private-limited",
  "/company/aayush-unihealth-private-limited",
  "/company/aayushaadya-nutrition-private-limited",
  "/company/aayushi-accutax-services-opc-private-limited",
  "/company/aayushka-fashion-private-limited",
  "/company/aayushree-ayurveda-india-private-limited",
  "/company/aayushree-technologies-india-private-limited",
  "/company/aayuvardan-lifescience-private-limited",
  "/company/aayuwell-health-foundation",
  "/company/aayzan-enterprise-private-limited",
  "/company/aazad-m-technology-private-limited",
  "/company/aazham-tech-labs-private-limited",
  "/company/aazhi-seafoods-private-limited",
  "/company/aazhi-spicex-import-and-export-private-limited",
  "/company/aazhisai-solutions-private-limited",
  "/company/aazhiyar-technologies-opc-private-limited",
  "/company/aazima-medical-private-limited",
  "/company/aazoob-technology-private-limited",
  "/company/aazu-hospitality-services-private-limited",
  "/company/ab-&&-dk-jute-products-private-limited",
  "/company/ab-atelier-opc-private-limited",
  "/company/ab-bros-holidays-private-limited",
  "/company/ab-dcode7-technologies-private-limited",
  "/company/ab-farmerscape-private-limited",
  "/company/ab-feeds-private-limited",
  "/company/ab-koourier-&&-logistics-private-limited",
  "/company/ab-lets-enjoy-tour-planners-private-limited",
  "/company/ab-mount-kraft-interiors-&&-services-private-limited",
  "/company/ab-patrons-private-limited",
  "/company/ab-powermatics-private-limited",
  "/company/ab-scientific-opc-private-limited",
  "/company/ab-seventh-key-private-limited",
  "/company/ab-supporting-factor-opc-private-limited",
  "/company/ab-hi-futuretech-private-limited",
  "/company/ab7arjunbhatta-broadcasting-private-limited",
  "/company/aba-advisors-private-limited",
  "/company/aba-designing-solutions-opc-private-limited",
  "/company/aba-everythink-design-studio-private-limited",
  "/company/abaac-services-private-limited",
  "/company/abaam-content-trading-private-limited",
  "/company/abaan-confectionary-private-limited",
  "/company/ababil-enterprise-tour-and-travels-opc-private-limited",
  "/company/ababil-mart-private-limited",
  "/company/abacus-brainiac-centre-opc-private-limited",
  "/company/abadah-financial-advisory-private-limited",
  "/company/abadh-mart-india-private-limited",
  "/company/abaga-solutions-private-limited",
  "/company/abags-foundation",
  "/company/abam-engineers-private-limited",
  "/company/abam-pro-cosmetics-private-limited",
  "/company/aban-entertainment-private-limited",
  "/company/abansakhi-universal-private-limited",
  "/company/abanta-cold-store-private-limited",
  "/company/abanta-seafoods-private-limited",
  "/company/abar-capital-advisors-private-limited",
  "/company/abar-jewels-private-limited",
  "/company/abar-mata-mahila-aajeevika-farmer-producer-company-limited",
  "/company/abata-ai-private-limited",
  "/company/abava-diagnostic-private-limited",
  "/company/abaxo-agritech-private-limited",
  "/company/abbas-foundation",
  "/company/abbhani-foods-private-limited",
  "/company/abbhay-elitte-private-limited",
  "/company/abbm-industries-private-limited",
  "/company/abbs-infrastructure-private-limited",
  "/company/abbtron-nextgen-private-limited",
  "/company/abc-advance-engineerings-private-limited",
  "/company/abc-infratech-engineering-limited",
  "/company/abccet-placement-services-private-limited",
  "/company/abcde-mission-edtech-private-limited",
  "/company/abcdesign-technologies-private-limited",
  "/company/abcgo-business-solutions-private-limited",
  "/company/abchi-infrastructure-private-limited",
  "/company/abci-social-foundation",
  "/company/abcl-ecommerce-service-private-limited",
  "/company/abcn-solutions-private-limited",
  "/company/abco-ipeople-infosystems-private-limited",
  "/company/abcon-advisory-private-limited",
  "/company/abcp-solutions-private-limited",
  "/company/abcr-infra-projects-private-limited",
  "/company/abcs-trading-and-consultancy-private-limited",
  "/company/abd-forex-private-limited",
  "/company/abd360-sports-opc-private-limited",
  "/company/abdaniya-builders-private-limited",
  "/company/abdbhatt-consultancy-opc-private-limited",
  "/company/abdias-institute-&&-study-abroad-private-limited",
  "/company/abdiel-healthcare-private-limited",
  "/company/abdolphin-infratech-township-private-limited",
  "/company/abdr-links-private-limited",
  "/company/abdul-aziz-social-foundation",
  "/company/abdul-hakeem-contracting-private-limited",
  "/company/abdul-kader-white-fly-trading-private-limited",
  "/company/abdul-samad-tourism-india-private-limited",
  "/company/abdulkhalik-education-and-welfare-foundation",
  "/company/abdulla-marketjourney-ventures-private-limited",
  "/company/abdullah-international-private-limited",
  "/company/abdullah-maniyar-foundation",
  "/company/abdullah-tours-private-limited",
  "/company/abdw-association",
  "/company/abe-engineering-solutions-private-limited",
  "/company/abedi-global-private-limited",
  "/company/abeeha-retail-private-limited",
  "/company/abeer-motion-picture-private-limited",
  "/company/abelia-platform-services-private-limited",
  "/company/abellian-cosmetics-and-wellness-private-limited",
  "/company/abellon-waste-management-limited",
  "/company/abellon-waste-recycling-limited",
  "/company/abellona-agrotech-private-limited",
  "/company/aberdeen-container-lines-private-limited",
  "/company/abesit-incubation-forum",
  "/company/abetrans-global-logistics-private-limited",
  "/company/abeyo-ventures-private-limited",
  "/company/abf-care-private-limited",
  "/company/abf-micro-services-association",
  "/company/abfl-import-export-private-limited",
  "/company/abg-constrotech-private-limited",
  "/company/abg-facilities-management-private-limited",
  "/company/abg-green-infra-private-limited",
  "/company/abgo-social-welfare-foundation",
  "/company/abgrk-rise-the-world-foundation",
  "/company/abh-industries-private-limited",
  "/company/abha-asomi-mahila-farmers-producer-company-limited",
  "/company/abha-devi-farmer-producer-company-limited",
  "/company/abha-electronics-limited",
  "/company/abha-fleet-limited",
  "/company/abha-healing-foundation",
  "/company/abha-infotech-private-limited",
  "/company/abha-infraventures-private-limited",
  "/company/abha-innovative-utavi-opc-private-limited",
  "/company/abha-space-research-organization-private-limited",
  "/company/abhaashish-franchises-opc-private-limited",
  "/company/abhang-technologies-private-limited",
  "/company/abhans-work-hirex-private-limited",
  "/company/abhansh-trading-services-private-limited",
  "/company/abhasi-foundation",
  "/company/abhassa-global-trade-private-limited",
  "/company/abhava-partners-opc-private-limited",
  "/company/abhay-cabzone-india-private-limited",
  "/company/abhay-catering-private-limited",
  "/company/abhay-defender-security-opc-private-limited",
  "/company/abhaya-hasta-infra-private-limited",
  "/company/abhaya-nayan-engineering-private-limited",
  "/company/abhayaditya-infrastructures-private-limited",
  "/company/abhayam-charitable-foundation",
  "/company/abhayam-fintech-private-limited",
  "/company/abhayamm-agritech-private-limited",
  "/company/abhayamm-pharma-private-limited",
  "/company/abhayapuri-engineering-private-limited",
  "/company/abhaydivyansh-tv24-news-network-private-limited",
  "/company/abhaygrow-micro-finance-private-limited",
  "/company/abhayguru-investment-services-private-limited",
  "/company/abhed-pharmaceuticals-limited",
  "/company/abhedalaxmi-entertainment-ventures-private-limited",
  "/company/abhedya-projects-private-limited",
  "/company/abheswari-farmer-producer-company-limited",
  "/company/abhg-trading-private-limited",
  "/company/abhhay-multiservices-private-limited",
  "/company/abhi-&&-sanvi-edu-private-limited",
  "/company/abhi-aero-and-tech-private-limited",
  "/company/abhi-anmol-bharat-private-limited",
  "/company/abhi-commodities-private-limited",
  "/company/abhi-fabrication-engineering-opc-private-limited",
  "/company/abhi-manpower-solutions-private-limited",
  "/company/abhi-motors-private-limited",
  "/company/abhi-multiventure-private-limited",
  "/company/abhi-one-pay-suvidha-private-limited",
  "/company/abhi-vandya-foundation",
  "/company/abhidha-services-private-limited",
  "/company/abhidhana-small-microcare-association",
  "/company/abhidharam-advisory-private-limited",
  "/company/abhidharma-corporations-private-limited",
  "/company/abhidurga-infratech-private-limited",
  "/company/abhigiri-farmers-producer-company-limited",
  "/company/abhigya-micro-foundation",
  "/company/abhigya-projects-opc-private-limited",
  "/company/abhigyan-aiq-private-limited",
  "/company/abhigyan-realty-ventures-private-limited",
  "/company/abhigyan-trading-india-private-limited",
  "/company/abhihava-corporate-consultants-private-limited",
  "/company/abhijay-purecane-beverages-private-limited",
  "/company/abhijeetbatsa-empowering-dreams-private-limited",
  "/company/abhijit-hospitality-private-limited",
  "/company/abhijnana-food-products-private-limited",
  "/company/abhijyoti-real-estate-private-limited",
  "/company/abhik-buildcon-private-limited",
  "/company/abhikant-foundation",
  "/company/abhikar-fusioncraft-private-limited",
  "/company/abhikush-fusion-private-limited",
  "/company/abhilash-welfare-foundation",
  "/company/abhilasha-mahila-producer-company-limited",
  "/company/abhilashabazar-india-private-limited",
  "/company/abhim-it-solution-private-limited",
  "/company/abhima-bio-fuels-private-limited",
  "/company/abhiman-agro-processing-and-manufacturing-farmer-producer-company-limited",
  "/company/abhiman-studios-private-limited",
  "/company/abhimanyuborna-manpower-supplier-private-limited",
  "/company/abhimith-wasteless-services-private-limited",
  "/company/abhimora-infra-projects-private-limited",
  "/company/abhin-abhinaya-private-limited",
  "/company/abhin-security-services-private-limited",
  "/company/abhinandan-baanvi-construction-private-limited",
  "/company/abhinandan-traders-scrap-private-limited",
  "/company/abhinav-biomass-agrocare-private-limited",
  "/company/abhinav-kala-kendra-private-limited",
  "/company/abhinav-softech-private-limited",
  "/company/abhinav-vivah-private-limited",
  "/company/abhinava-info-technologies-opc-private-limited",
  "/company/abhinava-realty-&&-constructions-private-limited",
  "/company/abhinava-strategic-partners-private-limited",
  "/company/abhinavagupta-institute-of-advanced-studies-foundation",
  "/company/abhinavata-govriddhi-tech-solutions-opc-private-limited",
  "/company/abhinavedutech-private-limited",
  "/company/abhinaya-innovations-and-sensor-tech-private-limited",
  "/company/abhininsta-forexwise-private-limited",
  "/company/abhinova-labs-private-limited",
  "/company/abhiom-solar-solutions-private-limited",
  "/company/abhipada-consulting-private-limited",
  "/company/abhipay-infotech-private-limited",
  "/company/abhipray-construction-private-limited",
  "/company/abhipriya-trade-connect-private-limited",
  "/company/abhir-constrotech-private-limited",
  "/company/abhiraami-international-private-limited",
  "/company/abhiraj-buildcon-realestate-consultancy-private-limited",
  "/company/abhiraj-foundation",
  "/company/abhiraj-hvac-private-limited",
  "/company/abhiraj-infrabuild-private-limited",
  "/company/abhirajs-kitchen-concepts-private-limited",
  "/company/abhiram-biotech-opc-private-limited",
  "/company/abhiram-educational-lab-furnishing-private-limited",
  "/company/abhirama-constructions-private-limited",
  "/company/abhirama-creations-private-limited",
  "/company/abhirama-life-sciences-private-limited",
  "/company/abhirama-promoters-and-developers-private-limited",
  "/company/abhirishi-infra-private-limited",
  "/company/abhiroh-auxiliary-services-private-limited",
  "/company/abhiruchi-infra-private-limited",
  "/company/abhiruchi-masale-center-private-limited",
  "/company/abhiruchir-foodtech-association",
  "/company/abhisa-power-and-infra-private-limited",
  "/company/abhisaar-sikshan-private-limited",
  "/company/abhisan-hospitality-private-limited",
  "/company/abhisani-traders-private-limited",
  "/company/abhisarika-foundation",
  "/company/abhisha-real-estate-developers-private-limited",
  "/company/abhishara-medical-opc-private-limited",
  "/company/abhishek-gajanan-mahalle-realty-private-limited",
  "/company/abhishekbarwal-trading-private-limited",
  "/company/abhishree-fashion-private-limited",
  "/company/abhishta-grand-enterprise-private-limited",
  "/company/abhishtajewelcraft-private-limited",
  "/company/abhisree-operations-opc-private-limited",
  "/company/abhisweta-real-estate-private-limited",
  "/company/abhith-manpower-services-private-limited",
  "/company/abhith-siksha-private-limited",
  "/company/abhitosh-merchandise-private-limited",
  "/company/abhitri-foods-and-beverage-private-limited",
  "/company/abhiunnat-jaivik-producer-company-limited",
  "/company/abhivardhan-agrotech-private-limited",
  "/company/abhivelrajan-private-limited",
  "/company/abhivention-squad-dance-studio-private-limited",
  "/company/abhiverdhya-industries-private-limited",
  "/company/abhividha-foundation",
  "/company/abhivridhi-warehousing-private-limited",
  "/company/abhivrit-farms-private-limited",
  "/company/abhivrtti-india-private-limited",
  "/company/abhivruddhi-social-welfare-foundation",
  "/company/abhiwadan-green-private-limited",
  "/company/abhiyanka-tour-and-travels-private-limited",
  "/company/abhiyanta-calibration-lab-&&-research-centre-opc-private-limited",
  "/company/abhm-jay-foundation",
  "/company/abhnik-agro-private-limited",
  "/company/abhra-innovations-private-limited",
  "/company/abhrankash-healthcare-private-limited",
  "/company/abhudya-utthan-foundation",
  "/company/abhush-enterprises-private-limited",
  "/company/abhyaanch-solutions-opc-private-limited",
  "/company/abhyaanugraha-fed-farmer-producer-company-limited",
  "/company/abhyaasa-international-school-private-limited",
  "/company/abhyam-imperials-securtas-private-limited",
  "/company/abhyankar-alliance-private-limited",
  "/company/abhyankara-agro-farmers-producer-company-limited",
  "/company/abhyant-distribution-private-limited",
  "/company/abhyant-solutions-private-limited",
  "/company/abhyarang-construction-private-limited",
  "/company/abhyaranyan-hospitality-private-limited",
  "/company/abhyaroha-foundation",
  "/company/abhyas-cognitive-labs-private-limited",
  "/company/abhyas-lean-and-digital-services-private-limited",
  "/company/abhyasarth-foundation",
  "/company/abhyuday-solar-energy-private-limited",
  "/company/abhyudaya-e-waste-private-limited",
  "/company/abhyunati-financial-services-private-limited",
  "/company/abhyunati-infrastructure-private-limited",
  "/company/abhyuv-infracom-private-limited",
  "/company/abi-sweets-and-pastries-private-limited",
  "/company/abiaksh-solutions-private-limited",
  "/company/abida-infra-ventures-private-limited",
  "/company/abiffa-international-private-limited",
  "/company/abijoval-global-traders-and-developers-private-limited",
  "/company/abilities-innovative-products-&&-technologies-limited",
  "/company/abilitrix-private-limited",
  "/company/ability-advocacy-private-limited",
  "/company/ability-fusion-private-limited",
  "/company/ability-industries-private-limited",
  "/company/ability-seafoods-private-limited",
  "/company/abim-studio-private-limited",
  "/company/abimo-globex-private-limited",
  "/company/abinandhika-constructions-private-limited",
  "/company/abine-india-private-limited",
  "/company/abinnovo-tech-private-limited",
  "/company/abinyak-embroidery-and-pottery-services-opc-private-limited",
  "/company/abiopharm-innovations-private-limited",
  "/company/abir-ayurveda-private-limited",
  "/company/abira-craftscape-private-limited",
  "/company/abirami-builder-&&-promoter-private-limited",
  "/company/abirami-convention-centre-private-limited",
  "/company/abirami-granites-private-limited",
  "/company/abirami-green-energy-private-limited",
  "/company/abiramy-annapoorna-restaurant-private-limited",
  "/company/abirata-services-foundation",
  "/company/abirbhab-services-private-limited",
  "/company/abiron-private-limited",
  "/company/abiroo-strategyz-technologies-private-limited",
  "/company/abis-bio-science-private-limited",
  "/company/abisar-resources-opc-private-limited",
  "/company/abisenthil-abroad-education-consultancy-private-limited",
  "/company/abiswas-technology-private-limited",
  "/company/abivirthi-jewellery-private-limited",
  "/company/abivirthi-traders-private-limited",
  "/company/abiwe-innovation-private-limited",
  "/company/abj-construction-private-limited",
  "/company/abjavallabha-farmer-producer-company-limited",
  "/company/abjayonih-private-limited",
  "/company/abjey-trading-ventures-private-limited",
  "/company/abjm-media-foundation",
  "/company/abjumbo-bestgamez-private-limited",
  "/company/abk-steel-supply-private-limited",
  "/company/abkglobal-impex-private-limited",
  "/company/abkh-consultancy-opc-private-limited",
  "/company/abksons-private-limited",
]





console.log("inside background.js");

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function makeApiCall( form_details) {
  userData.push(form_details)
}

async function isValidUrl(url) {
  try {
    const response = await fetch(url, { method: "HEAD" });
    return response.ok;
  } catch (error) {
    console.error("Error checking URL validity:", error,url);
    return false;
  }
}

chrome.runtime.onMessage.addListener(async function (
  message,
  sender,
  sendResponse
) {
  if (message.action === "next_link") {
    console.log("sender -- :-- ", sender);
    console.log("sendResponse -- :-- ", sendResponse);
    // processing = false;
    // processNextLink();
    console.log(message);
    closeTheTab( message?.form_details);
  } else if (message.action === "closeTab") {
    chrome.tabs.remove(sender?.tab?.id);
  }
});

async function processNextLink() {
  // Check if there are links to process and if not already processing
  if (index < links.length && !processing) {
    processing = true;

    const data = links[index++];
    const link = data;

    discardData = data;
    // Create a new tab with the link URL
    if (await isValidUrl(`https://www.companydetails.in${link}`)) {
      chrome.tabs.create({ url: `https://www.companydetails.in${link}`, active: true }, async function (tab) {
        if (chrome.runtime.lastError || !tab) {
          console.error(
            "Error creating or accessing tab:",
            chrome.runtime.lastError
          );
          processing = false; // Reset processing flag
          return;
        }
        tabData = tab;
      });
    } else {
      console.log("Invalid url skipped");
      makeApiCall("Invalid url skipped", "Invalid url");
      processing = false;
      processNextLink();
      return;
    }
  } else {
    console.log("All links processed.");
    console.log(userData,"all Data")
  }
}

async function closeTheTab( form_details) {
  console.log(userData,"userData")
  try {
    chrome.tabs.remove(tabData.id, async function () {
      await makeApiCall( form_details);
      // Continue to the next link
      console.log("removing the tab");
      processing = false;
      processNextLink();
    });
  } catch (error) {
    await makeApiCall( form_details);
    // Continue to the next link
    console.log("inside the error of close tab", error);
    processing = false;
    processNextLink();
  }
}

processNextLink()